### ISSUE TITLE
Disable dragging of nodes

### ISSUE THREAD

**Issue by maurocolella** [fritz-c/react-sortable-tree#14]
Hello,

Thank you for that awesome component. I realize I can maintain the state of my tree if I simply do not update the state on change, but is it possible to disable the dragging of nodes?

**Comment by fritz-c** [comment]
You could create a CSS rule for the drag handle, something like:
```css
.rst__moveHandle {
    display: none;
}

.rst__rowContents {
    border-left: 1px solid #bbb;
}
```
The above will hide the handle, making dragging impossible. An alternative would be to apply `pointer-events: none;` to the handle, but that would leave you with a UI that suggests you can drag stuff around even though you can't.

If you want to apply this to only a few nodes in the tree, I would recommend (>= v0.1.5) adding something like `data-hide-handle: 'true'` in `generateNodeProps` to nodes that fit the hiding conditions, and then a css selector to the css above (something like `[data-hide-handle="true"] .rst__moveHandle {...`).
