### ISSUE TITLE
[Discussion] Switch Back to CSS Modules

### ISSUE THREAD

**Issue by arvinxx** [fritz-c/react-sortable-tree#254]
At first thank you very much for this awsome library! And I just try v2.0.1 and use the newest feature - overwitte css. And after my experiment of it, I ask to switch back to CSS Modules.
let me explain why.
my propose is to customize the style,so I need to recongize the structure of the component.Because of I can't dive into source code to change style, what I did is to use the hardcode css background to figure it out. Actually it's painful.
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180218/CHaeBA40HH.png)
Then,when I try to customize the  block size. Thank to less I can define some varibale to change block size
block size. But the is another porblem.
You can see there is lot's inline style in Nodes. If I want to change it I need use `!important` command. Alright, It's not a big deal.Let's go on.

![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180218/E67HJkBd5H.png)
```less
@rst-mg: 33px;
.rst__ {
  &lineBlock {
    width: @rst-mg !important;
    background: saddlebrown;
  }
 &lineBlock {
    width: @rst-mg !important;
    background: saddlebrown;
  }
  &lineHalfHorizontalRight {
    display: inline-block;
    width: @rst-mg !important;
    background: lavender;
  }
}
```
But what is worse is after that: because of those inline style.When I use `!important` , some imortant style was overwritten.
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180218/GhBEHdjiHD.png)
![mark](http://oxnc5ug9u.bkt.clouddn.com/pic/180218/gc5eHl55eh.png)

It was horrible. what should I to to change this inline style when it couple with function tightly? Can pure CSS or Less/Scss handle with it?

I think overwritte CSS looks user-friendly at first time , but when you dive into real usage, I will be less flexible and introduce more problems.

So I propuse to switch back to CSS Modules. As for more friend customization ,I think more friendly way is to wirte a complete guide other than just use pure css.Or define more class prop for different part? I don't know.
@brendanmoore  @fritz-c 

Here is my overwitten less. 
```less
@rst-mg: 33px;
.rst__ {
  &tree {
    background: rosybrown;
    padding: 24px;
  }
  &node {
    height: 24px !important;
  }
  &lineBlock {
    width: @rst-mg !important;
    background: saddlebrown;
  }
  &lineHalfHorizontalRight {
    display: inline-block;
    width: @rst-mg !important;
    background: lavender;

    &::before {
      width: 0;
    }
    &::after {
      height: 100%;
    }
    &:hover {
      cursor: pointer;
    }

  }
  &nodeContent{
    background: darkmagenta;
    left: @rst-mg !important;

  }
  &lineHalfHorizontalRight:hover > &collapseButton {
    visibility: hidden;
  }
  &collapseButton {
    height: 24px;
    width: 24px;
    left: -1*@rst-mg/2 !important;
    background: darkcyan;
    box-shadow: none;
    &::after {
      content: "";
      display: inline-block;
      height: 1px;
      width: 10px;
      background: red;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
    &:focus {
      box-shadow: none;
      height: 24px;
      ::selection {
        display: none;
      }
    }
    &:hover {
      &:not(:active) {
        background: yellowgreen;
        height: 24px;
        width: 24px;
      }

    }
  }

  &lineChildren {
    display: none;
  }
  &rowWrapper {
    padding: 0;
  }
  &moveHandle {
    width: 4px;
    height: 4px;
    padding: 3px;
    border: 0;
    border-radius: 50%;
    margin: 5px;
    background: #666;
    box-shadow: 0 0;

    z-index: 1;
    cursor: pointer;
  }
  &row {
    align-items: center;
  }

  &rowContents {
    position: relative;
    font-size: 14px;
    line-height: 22px;
    display: flex;
    -webkit-box-flex: 1;
    -ms-flex: 1 0 auto;
    flex: 1 0 auto;
    -webkit-box-pack: justify;
    justify-content: space-between;
    -webkit-box-align: center;
    align-items: center;

    min-width: 230px;
    height: 100%;
    padding: 0 5px 0 10px;
    border: none;
    border-left: none;
    border-radius: 4px;
    box-shadow: 0 0;
  }

}

```
jsx
```jsx
import React, { Component } from 'react';
import SortableTree from 'react-sortable-tree';
import 'react-sortable-tree/style.css'; // This only needs to be imported once in your app
import './SortableTree.less';

export default class Tree extends Component {
  constructor(props) {
    super(props);

    this.state = {
      treeData: [{ title: 'Chicken', children: [{ title: 'Egg' }] }],
    };
  }

  render() {
    return (
      <div style={{height:800}}>
        <SortableTree
          treeData={this.state.treeData}
          onChange={treeData => this.setState({ treeData })}
        />
      </div>
    );
  }
}

```
